"use client";

import React, { useState, useEffect } from "react";
import Sidebar from "@/components/admin/Sidebar";
import {
  BarChart3Icon,
  FileTextIcon,
  MenuIcon,
  SettingsIcon,
  XIcon,
} from "lucide-react";

const MainContent: React.FC = () => {
  return (
    <div className="p-4 sm:p-6 lg:p-8 text-slate-800 dark:text-slate-200">
      <h1 className="text-3xl font-bold mb-6">Overview</h1>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        <div className="bg-white dark:bg-slate-800/50 p-6 rounded-xl shadow-md hover:shadow-lg transition-shadow duration-300">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-slate-700 dark:text-slate-300">
              Quarterly Revenue
            </h2>
            <BarChart3Icon className="w-6 h-6 text-sky-500" />
          </div>
          <p className="text-4xl font-bold mt-4">$1.2M</p>
          <p className="text-sm text-green-500 mt-1">+12% from last quarter</p>
        </div>

        <div className="bg-white dark:bg-slate-800/50 p-6 rounded-xl shadow-md hover:shadow-lg transition-shadow duration-300">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-slate-700 dark:text-slate-300">
              Active Reports
            </h2>
            <FileTextIcon className="w-6 h-6 text-amber-500" />
          </div>
          <p className="text-4xl font-bold mt-4">34</p>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            2 reports pending review
          </p>
        </div>

        <div className="bg-white dark:bg-slate-800/50 p-6 rounded-xl shadow-md hover:shadow-lg transition-shadow duration-300">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-slate-700 dark:text-slate-300">
              System Health
            </h2>
            <SettingsIcon className="w-6 h-6 text-indigo-500" />
          </div>
          <p className="text-4xl font-bold mt-4">99.8%</p>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Uptime over last 30 days
          </p>
        </div>
      </div>

      <div className="mt-8 bg-white dark:bg-slate-800/50 p-6 rounded-xl shadow-md">
        <h2 className="text-xl font-semibold mb-4">Recent Activity</h2>
        <div className="space-y-4">
          <div className="flex items-center justify-between p-3 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-700/50">
            <div>
              <p className="font-medium">Monthly Financials Q2 2024</p>
              <p className="text-sm text-slate-500 dark:text-slate-400">
                Generated by Alex
              </p>
            </div>
            <span className="text-sm text-slate-500">2 hours ago</span>
          </div>
          <div className="flex items-center justify-between p-3 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-700/50">
            <div>
              <p className="font-medium">Operations Dashboard Updated</p>
              <p className="text-sm text-slate-500 dark:text-slate-400">
                System Automation
              </p>
            </div>
            <span className="text-sm text-slate-500">Yesterday</span>
          </div>
          <div className="flex items-center justify-between p-3 rounded-lg hover:bg-slate-100 dark:hover:bg-slate-700/50">
            <div>
              <p className="font-medium">New BI Metric: "User Churn Rate"</p>
              <p className="text-sm text-slate-500 dark:text-slate-400">
                Added by Jane
              </p>
            </div>
            <span className="text-sm text-slate-500">3 days ago</span>
          </div>
        </div>
      </div>
    </div>
  );
};

const App: React.FC = () => {
  const [isSidebarExpanded, setSidebarExpanded] = useState(false);
  const [isMobileOpen, setMobileOpen] = useState(false);
  const [isMobile, setIsMobile] = useState(false);

  useEffect(() => {
    const handleResize = () => {
      const mobile = window.innerWidth < 768;
      setIsMobile(mobile);
      if (!mobile) {
        setMobileOpen(false);
      }
    };
    handleResize();
    window.addEventListener("resize", handleResize);
    return () => window.removeEventListener("resize", handleResize);
  }, []);

  const handleMouseEnter = () => {
    if (!isMobile) {
      setSidebarExpanded(true);
    }
  };

  const handleMouseLeave = () => {
    if (!isMobile) {
      setSidebarExpanded(false);
    }
  };

  return (
    <div className="relative min-h-screen">
      {isMobile && (
        <header className="fixed top-0 left-0 right-0 h-16 bg-slate-50/80 dark:bg-slate-950/80 backdrop-blur-sm flex items-center px-4 z-30 border-b border-slate-200 dark:border-slate-800">
          <button
            className="p-2 text-slate-600 dark:text-slate-300"
            onClick={() => setMobileOpen(!isMobileOpen)}
          >
            {isMobileOpen ? (
              <XIcon className="w-6 h-6" />
            ) : (
              <MenuIcon className="w-6 h-6" />
            )}
          </button>
          <div className="flex-1 text-center font-bold text-lg text-slate-800 dark:text-slate-200">
            Dashboard
          </div>
        </header>
      )}

      <Sidebar
        isMobile={isMobile}
        mobileOpen={isMobileOpen}
        isExpanded={isSidebarExpanded}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
      />

      {isMobile && isMobileOpen && (
        <div
          className="fixed inset-0 bg-black bg-opacity-50 z-30"
          onClick={() => setMobileOpen(false)}
        />
      )}

      <main
        className={`transition-all duration-300 ease-in-out
          ${isMobile ? "pt-16" : isSidebarExpanded ? "ml-64" : "ml-20"}`}
      >
        <MainContent />
      </main>
    </div>
  );
};

export default App;
